### ISSUE TITLE
What you think about Gulp4 and core behind it?

### ISSUE THREAD

**Issue by tunnckoCore** [matthewmueller/ama#10]
Upcoming v4 and core `async-done`, `bach` and `undertaker`

**Comment by matthewmueller** [comment]
I don't use gulp, so I haven't really been following it.

**Comment by tunnckoCore** [comment]
> I don't use gulp, so I haven't really been following it.

Hah, that's amazing! :D cant believe, one more like me. I also dont use it, but follow the stuff around and doing some things with @jonschlinkert and @doowb inspired by gulp team.
