### ISSUE TITLE
What do you think of Riot.js?

### ISSUE THREAD

**Issue by bendik** [matthewmueller/ama#14]
I've notices you've been picking up some React lately. :)

I'm personally holding off React due to its not so sassy syntax, and its size compared to [Riot.js](http://riotjs.com) and wonder what opinion you might have established on this library.

**Comment by matthewmueller** [comment]
Good question. I haven't evaluated Riot, but your concerns about React are definitely valid. The syntax is manageable and may even grow on you a little bit, but the file size is problematic as well as the singleton pattern they're using.

If I step away from React, the first thing I'd try is https://github.com/ashaffer/vdux. 

Hope this helps a little anyway :-)

**Comment by bendik** [comment]
Thanks for this answer. I've now tried out both for a small project. Your recommendation provided the least trouble when it came to diffing with style-properties. Hence it's a winning answer! :)
