### ISSUE TITLE
 Which fictional character do you believe is the most like yourself? 

### ISSUE THREAD

**Issue by arthurvr** [matthewmueller/ama#2]

**Comment by matthewmueller** [comment]
I don't read too much fiction (though I want to more), but I would have to say that I relate most to Santiago, the protagonist from [The Alchemist](https://en.wikipedia.org/wiki/The_Alchemist_%28novel%29). 

Santiago in the book is optimistic, thoughtful (in this context: thought full), and a wanderer. These are all characteristics I see in myself.
