### ISSUE TITLE
Thoughts about RegExps project?

### ISSUE THREAD

**Issue by tunnckoCore** [matthewmueller/ama#9]
That's a big idea and project, and have many steps to do more.
- [RegExps Github Organization](https://github.com/regexps)
- [meta stuff repository](https://github.com/regexps/meta)
- [General discussion and roadmap](https://github.com/regexps/meta/issues/16)
- [more big and older "first hit" discussion](https://github.com/regexps/meta/issues/2)

In general  - centralized place for regular expression world for all languages. Just we are javascripters and we start with it.

[https://github.com/tunnckoCore/ama](https://github.com/tunnckoCore/messages)

**Comment by matthewmueller** [comment]
I like it! Definitely really good quality regexps are hard to come by. I tend to roll my own and modify when things break, but I will definitely check out your repo next time I'm in need of some good regexp :-)

**Comment by tunnckoCore** [comment]
Ha, cool to hear from you, thanks! :)
I've just started to think that im doing wrong with that project or communication with the community, so two devs @arthurvr and @sindresorhus blocked me with no reasons, which was.. WAW. Dont mind. :)

I've just trying to do some community around regular expressions world wide, cuz it missing, imo.

And there's one of the best `mentions-regex` (101% twitter compitable) and `youtube-regex`, also `hex-color-regex` (partially thanks to component team)
